[build]
  base = "frontend"
<<<<<<< HEAD
  publish = "dist"
=======
  publish = "frontend/dist"
>>>>>>> upstream/main
  command = "pnpm install && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
